language: ruby
rvm:
- 2.3.0
cache:
  bundler: true
before_install:
- gem update --system
- gem --version
- chmod +x ./_utils/*
- "./_utils/ci_generate.sh"
script:
- bundle exec jekyll build
- "./_utils/ci_prepare_deploy.sh"
after_success:
- "./_utils/ci_deploy.sh"
env:
  global:
  - JEKYLL_ENV=production
  - ENCRYPTION_LABEL=dff9f3dc1b4c
  - secure: yEZr5wbw8D0eoVBT4RQsUqi1lB1BiUZhhXMKGNWYd1BwPXTFJZDgvn3AFVGfCRxbzafQtHQ24SMzlV4tw1OKp9QbCMh26+GyCm1I6JeuruRkNz8bsKyJ/18yGddHeiJc8qLbAHmTUiZTcuxmQVmWI5vP2Mb3FrhjDQpOWT00W3T/s5d1DNZZxWQUqtmLm41LVGq6zyCBr10lrz2bqiMJhfsQ3GhylGE+kGFk4m5ATgK9+BJvayy7bSoF/z/B1qJc3Gix/41Tv+JC9CxHfQqQFNpPwxDZMLhKSPNGQ4TqFGiZ43/3SsSp/2+5PNPynBUv7cGpGAOewEP1N7W0eO0NhevkGmeBDahzH2mwG8EWjUd+zb5SbQf4z2cUQ/ZjKqDtacbfwcYmDvH4wMhulEOdoQUMEXzhKTQVL+YAVjKcEF908oYhYPBWClV15JaEtiqtqXlChuGXAIxGKbWDIQYaUwl1nByclRt56t9tfFnfXf3SQ8stmZlYALKheRtuJNdRV8CZKeCiwdKjGDvpejeQT+cr6NdXTzY2k77fM9GecEBJcPTa2WkPCsoZ+hka/2fr5T8h+cy2dbY7/lcNyWZcDZ5G5HYHTgkq6qdZUPCniKNNnfNGudutZ1nifhF7ZC5VOaNjgXonDLF0qqsNeCGH1aJJ8AcZXOmWKNPnIBOnEBU=
  - secure: VJqBRaW2DWAeEdEr89IIF58z1npxVsechffmZT0RgeRYqNi/pbqLOwFVi6J9J6n1SsuVS+s1MEd0n6yVncVyUfGCU7+pD7o/Wij1HEtK02fYRsPXXkjSMZHkiipn3wOi5jVH6LFb4QFe7nuKJo8unTnEjdc9z9lyJ916ZN+4QAliDFrPO9SPNuoSQV+HXYUPfe+NCyWTDOyCvHK9/smBKL2CtV98oxJR6asegsqe/ntvziXy0t23dfadJcDSkePZ7zd28PtaXkAIua0MNKg65WBM5Rtg282UhxFPSDluND89+qvxYGdoU4NoWKxqAKflOVPX70JKgHtj25TBG9Y7of6cCcOyFVJ3dP+ewhydz2tWn73BZb1nkbwda/sHlCYZWsw0jV5rAZLimwpxGlTcKV79iLlqokSbagjmRrXCbNsyh8gK0z3s1Ibs1VOQZAQCMFx67d209nRdZQ22dYechkqoUdkzHAoY4xDzDZ0FXxyNxPYbX0XVWJsffzzAn/p99JgxiOAWtKky6zIr4PsG3C/WJ6qSNSsUgp+VPlTCus+UvkrgdEOcmS39lN6dgjog4I6Bs4LnbZ12UGjzIKkBNaJ1wixag8bXffXPvF7DDnErj8qs5ogELEfiBiywh+yYW8d8et9WEzaxtmuSqEGfWCA6AdO19EPCFzKyPHryozs=
  matrix:
  - BUILD_TARGET=QINIU
  - BUILD_TARGET=GITHUB_PAGES
notifications:
  slack:
    rooms:
    - secure: RQGKRURjyEmTKcJ/5trqS6EbBs3Zg68mBwYcv4e+j84D9ReGwDvnDCfiCOW2KAOz3WL+9to9LIVhp8AeKU6eKyOpZgD6OAnIAwlFHnjmb4wDTa54ShJFG+dVpUauXWeasPpNQj7TFG6IULw2isRwekwJcetBxxil/PWMFPbCsE17ug0xvJfC+T2RxiwK2HrgssrIntlVs8ZRSI+FZLtVQjMNN3UAz/8JJpPbc6nJ42JOETTa3x6EpYTa/BVLI6wACEo+QViWahVDcXEDwXmIWxRTFCM1TYQ7bMwNydAGTDGSoQRaMsTHGQBww35ssx5Q3S8hsl9SjaN8C0PAdN8mMd6b0UgpQ7lVHb5tMXLyLDoGXbS3bglDqi9diMMo46LPWSoe+L+VNbr4lYLmEw1Cq+qyyNOJTwFBZXih9hra/SiqX15CKtZyAB+uNSt1MgHDEs3HQ6g+DQWxHXLKFit3yWduFEwSTD8lrwrvach0mC0S/6pn89nrKN5x/8OEaEJpSqrT3B0zZ+uPIGAWfthvcIkktnu/O/d/O1MtHZWL5CFW/uKIajgDZx1DMQ0yUtUejZgBqyGoP4zEX/A4yfXkTBZQxaZ97pJqy/jdoLAv5n59wVcBzFnapFpo+MBXVJXFods/gwtx/5yo4dJ+TxlZ1pZB6EwatxijyBAK1oQ0iIs=
    - secure: iG5ixQqlQJ7sHUNXHxbuf3M0ZF8lZ/wSGPwoFVlWBMgWMsZ5jZwNxsYBY19WRDRqOJNRXfiNpnQBAfUuC0IEs+CvQMa4180tggBD/ZpRIOtYDBfSjqkqbmtPlKK6vdid4WIwOQ0WiNAiu3lYwcolLVNilHQKqR4WlBYE8QUM1/JBdiNG22rph8MqHqTqIxC5LGDRBDEuMRFVdHPr+QOQbE6SRA+bAeMnmfUghnOGF5IXIih0obDaXHDt5gjGLgtmogfH4XlL/wJuIZpPdp3Tcd4XRWIaUamqYMzduaGwPBXx5GYdcboh28/HJt65C2a1uvVAmWQTvhX/GPR2vWQ++hTBk/pmsAWmA2/gdp+Ci9sSouML/sb1G98wXzCqz4buEZPNq3Q45k4CttXx0pCCcFOWMqU0sF8Z1/+KIn++O03F7XW6THA1bJQbTxMKvJhFtwsY4FJoVnjHqebBPLUVscNF7i4qIzwssFXol2vZd89EymQbP6oVH73YnCJ/A8kOW5QhEglswnw2ZEHKSczwxI4mkAU9rpK/LNuW2K/LRybzwIZyLZLL0Qqw+dqrLJFHZel6a9tgUj/F9AFuK7B6GROcXknRrS1kw4sD11Aa/J+kemgFDdXQ3s4hyWvGcaJm+Hes3aNkY42I+rZhpCqyaWseLR/UbSBk1S4i0hjMbNs=
addons:
  apt:
    packages:
    - gettext
